title: My Hacker Blog
theme: jekyll-theme-hacker

kramdown:
  input: GFM
  hard_wrap: true

collections_dir: .

collections:
  oracle:
    output: true
    permalink: /oracle/:name/
  postgres:
    output: true
